version: '3.8'
services:
  web:
    build: .
    command: python app.py run -h 0.0.0.0
    ports:
      - "5000:5000"
      env_file: .env
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=iclinic
      - POSTGRES_PASSWORD=iclinic
      - POSTGRES_DB=dev_iclinic

volumes:
  postgres_data:
