swagger: '2.0'
info:
  description: Prescription API created for Iclinic Challenge
  version: 1.2.0
  title: Prescription API
  termsOfService: http://swagger.io/terms/
  contact:
    email: lauro.gama@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: gentle-harbor-62875.herokuapp.com
basePath: /
tags:
  - name: prescriptions
    description: Create medical prescriptions
    externalDocs:
      description: Find out more
      url: https://github.com/iclinic/iclinic-python-challenge
schemes:
  - https
paths:
  /prescriptions:
    post:
      tags:
        - prescriptions
      summary: Add a new prescription in the system
      description: ''
      operationId: addPrescription
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Prescription object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Prescription'
      responses:
        201:
          description: A new prescription was created
          schema:
            $ref: '#/definitions/201'
        404:
          description: Item not Found
          schema:
            $ref: '#/definitions/404'
        503:
          description: Service not Available
          schema:
            $ref: '#/definitions/503'
definitions:
  Prescription:
    type: object
    properties:
      clinic:
        $ref: '#/definitions/clinic'
      physician:
        $ref: '#/definitions/physician'
      patient:
        $ref: '#/definitions/patient'
      text:
        type: string
        example: Dipirona 1x ao dia
  clinic:
    type: object
    properties:
      id:
        type: integer
        format: int32
        example: 1
  physician:
    type: object
    properties:
      id:
        type: integer
        format: int32
        example: 1
  patient:
    type: object
    properties:
      id:
        type: integer
        format: int32
        example: 1
  201:
    type: object
    properties:
      data:
        type: object
        properties:
          clinic:
            $ref: '#/definitions/clinic'
          physician:
            $ref: '#/definitions/physician'
          patient:
            $ref: '#/definitions/patient'
          text:
            type: string
            example: Dipirona 1x ao dia
          metric:
            $ref: '#/definitions/metric'
  404:
    type: object
    properties:
      error: 
        type: object
        properties: 
          message: 
            type: string
            example: patient not found
          code: 
            type: string
            example: "03"
  503:
    type: object
    properties: 
      error: 
        type: object
        properties: 
          message: 
            type: string
            example: metrics service not available
          code: 
            type: string
            example: "04"
  metric: 
    type: object
    properties: 
      id: 
        type: integer
        format: int32
        example: 1
          